"""
Django settings for user_api project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-exf4)ko=9saty)7$_o-b36_&bx=45lyhfr#-j5$0-08tr5ip%n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['103.214.132.20','127.0.0.1','matrimonyapp.rainyseasun.com','tamizhimart.com', 'www.tamizhimart.com','192.168.1.8','192.168.1.11','192.168.1.5','192.168.1.19','vysyaadmin.rainyseasun.com','apiupg.rainyseasun.com','matrimonyapi.rainyseasun.com']
# ALLOWED_HOSTS = ['*']

ALLOWED_HOSTS = ['vsysmalamat-ejh3ftcdbnezhhfv.westus2-01.azurewebsites.net','polite-pond-0783ff91e.1.azurestaticapps.net','vysyamala.com','admin.vysyamala.com','calm-moss-0d969331e.2.azurestaticapps.net','localhost', '127.0.0.1','app.vysyamala.com','103.214.132.20']




CKEDITOR_UPLOAD_PATH = "ckeditor/images/"


DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'



# AZURE_ACCOUNT_NAME = 'vysyamaladev2025'  # Get from Azure Portal
# AZURE_ACCOUNT_KEY = '1mdfx0CBr1DTTNuVVK0qL5JXEpRNQnyWVEbIzndIPPlHXNERQIYGjsGWf3zXcX1EpRyCSu/hegkp+AStd8nkfQ=='  # Get from Azure Portal
# AZURE_CONTAINER = 'vysyamala'  # The name of your blob container
# AZURE_URL_EXPIRATION_SECS = None  # Optional: set expiry for signed URLs

# AZURE_CONNECTION_STRING = f'DefaultEndpointsProtocol=https;AccountName={AZURE_ACCOUNT_NAME};AccountKey={AZURE_ACCOUNT_KEY};EndpointSuffix=core.windows.net'

AZURE_ACCOUNT_NAME = 'vysyamat'  # Get from Azure Portal
AZURE_ACCOUNT_KEY = 'dDhUbtjX5Cp7RR30jOKQiHaPeAxjCEL85/uua4QEXzeDreSSThKsCGK98lr/Cl/KCvd3d5R1jACv+ASttEzBBg=='  # Get from Azure Portal
AZURE_CONTAINER = 'vysyamala'  # The name of your blob container
AZURE_URL_EXPIRATION_SECS = None  # Optional: set expiry for signed URLs
 
AZURE_CONNECTION_STRING = f'DefaultEndpointsProtocol=https;AccountName={AZURE_ACCOUNT_NAME};AccountKey={AZURE_ACCOUNT_KEY};EndpointSuffix=core.windows.net'



# AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=vysyamaladev2025;AccountKey=1mdfx0CBr1DTTNuVVK0qL5JXEpRNQnyWVEbIzndIPPlHXNERQIYGjsGWf3zXcX1EpRyCSu/hegkp+AStd8nkfQ==;EndpointSuffix=core.windows.net"  # Get from Azure Portal
# AZURE_BLOB_BASE_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER_NAME}"


# DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

MEDIA_URL = f'https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/'
MEDIA_ROOT = None  # No local file storage needed as we're using Azure

MEDIA_ROOT_1 = os.path.join(BASE_DIR, 'media')  # Or your preferred path

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'accounts',  
    'ckeditor',
    'ckeditor_uploader',
    'channels',
    'storages', 
    # 'oauth2_provider',
    
]

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]


# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
# ]

ROOT_URLCONF = 'user_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'psdadmin_vysyav2',
#         'USER': 'psdadmin_vysyav2',
#         'PASSWORD': 'rQfi0DADRo',
#         'HOST': 'bv-b29.yuvanetworks.in',  # e.g., 'localhost' or an IP address
#         'PORT': '3306',  # default MySQL port
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'vysamala_livedata',
#         'USER': 'vysyadev2025',
#         'PASSWORD': 'DevVy@2025',
#         'HOST': 'vysyadev.mysql.database.azure.com',  # e.g., 'localhost' or an IP address
#         'PORT': '3306'  # default MySQL port
#         # 'OPTIONS': {
#         #     'init_command': 'SET SESSION wait_timeout=28800',
#         #     'connect_timeout': 10
#         # }
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vysamala_livedata',
        'USER': 'vysyamala_new25',
        'PASSWORD': 'DevVy@2025',
        'HOST': 'vysyamat.mysql.database.azure.com',  # e.g., 'localhost' or an IP address
        'PORT': '3306',  # default MySQL port
        'CONN_MAX_AGE': 60, 
        # 'OPTIONS': {
        #     'init_command': 'SET SESSION wait_timeout=28800',
        #     'connect_timeout': 10
        # }
    }
}

#Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Cache directory inside project folder
# CACHE_DIR = BASE_DIR / 'cache'

# # Create directory if it doesn't exist
# CACHE_DIR.mkdir(exist_ok=True)

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         'LOCATION': str(CACHE_DIR),
#         'TIMEOUT': 3600,  # 1 hour cache timeout
#         'OPTIONS': {
#             'MAX_ENTRIES': 1000,
#         }
#     },
#     'images': {
#         'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         'LOCATION': str(BASE_DIR / 'cache' / 'images'),
#         'TIMEOUT': 86400,  # Longer timeout for images (1 day)
#         'OPTIONS': {'MAX_ENTRIES': 500}
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'psdadmin_vysmig',
#         'USER': 'psdadmin_vysmig',
#         'PASSWORD': 'IxmgB7H9zo',
#         'HOST': 'bv-b29.yuvanetworks.in',  # e.g., 'localhost' or an IP address
#         'PORT': '3306'  # default MySQL port
#         # 'OPTIONS': {
#         #     'init_command': 'SET SESSION wait_timeout=28800',
#         #     'connect_timeout': 10
#         # }
#     }
# }




# RAZORPAY_KEY_ID = "rzp_test_bR07kHwjYrmOHm"
# RAZORPAY_KEY_SECRET = "19D1bDjsZFN9Wh8xHHAqy5f0"

# RAZORPAY_KEY_ID = "rzp_live_uQLFO2SH0yNGCh"
# RAZORPAY_KEY_SECRET = "Nefg8B37WaHfPyjwMYt8xz90K"

RAZORPAY_KEY_ID = "rzp_live_HYCeDsho3jhHRt"
RAZORPAY_KEY_SECRET = "115FgMLvHHVQHlnjtT38zhzk"
 

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "https://polite-pond-0783ff91e.1.azurestaticapps.net",
    "https://calm-moss-0d969331e.2.azurestaticapps.net",
    "https://vysyamala.com",
    "https://admin.vysyamala.com",
    "https://vysyamala.com",
    "https://www.vysyamala.com",
    "https://vsysmalamat-ejh3ftcdbnezhhfv.westus2-01.azurewebsites.net",
    "https://app.vysyamala.com",
    "http://103.214.132.20:5173",
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TIME_ZONE = 'Asia/Kolkata'

DEFAULT_CHARSET = 'utf-8'

IMAGE_BASEURL = 'http://103.214.132.20:8000'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')





# Install channels_redis with pip install channels_redis
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }


#Commented by vinoth on 15th june 2025

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [("localhost", 6379)],  # Now works because Redis runs locally
#         },
#     },
# }

# AZURE_REDIS_HOST = 'vysyamala-redis.redis.cache.windows.net'
# AZURE_REDIS_KEY = 'MRum39q8JRawJ3lBM9Dd7qbSPmrdgZPC1AzCaGwflN8='  # Replace with your actual key

AZURE_REDIS_HOST = 'vysyamalamat.redis.cache.windows.net'
AZURE_REDIS_KEY = '3rD01MGuA9RO7XtSGp5PkwsMHOiMIKc6rAzCaPJd3BA='


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [(
#                 f"rediss://:{AZURE_REDIS_KEY}@{AZURE_REDIS_HOST}:6380/1"  # DB 1 for channels
#             )],
#             "ssl": True,
#         },
#     },
# }


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [{
                "address": f"rediss://:{AZURE_REDIS_KEY}@{AZURE_REDIS_HOST}:6380/1",
                "ssl": True,
                "ssl_cert_reqs": None,
            }]
            #"symmetric_encryption_keys": [SECRET_KEY],  # Optional but recommended
        },
    },
}

ASGI_APPLICATION = 'user_api.asgi.application'




CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"rediss://:{AZURE_REDIS_KEY}@{AZURE_REDIS_HOST}:6380/0",  # DB 0 for cache
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SSL": True,
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5
        }
    },
    'images': {  # This is the missing configuration
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"rediss://:{AZURE_REDIS_KEY}@{AZURE_REDIS_HOST}:6380/1",    # Using DB 1 for images
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}





CORS_ALLOW_HEADERS = [
    'content-type',
]


CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',
#     },
# }


# Assuming BASE_DIR is defined as the root of your project
BASE_DIR = Path(__file__).resolve().parent.parent

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'ERROR',  # Only log ERROR level or above to the file
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'error.log'),  # Store the log file inside the 'logs' folder
#             'formatter': 'verbose',  # Using the verbose format for detailed logs
#         },
#     },
#     'root': {
#         'handlers': ['file'],  # Direct logs to the file handler
#         'level': 'ERROR',  # Only capture errors or higher level logs
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],  # Log all Django-related logs to the file
#             'level': 'ERROR',
#             'propagate': True,
#         },
#         'authetication': {  # Replace 'your_app_name' with the name of your app if you want specific app-level logging
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }





# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'bv-b29.yuvanetworks.in'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'vinoth@psdigitise.com'
# EMAIL_HOST_PASSWORD = 'Vignesh@12160'
# DEFAULT_FROM_EMAIL = 'vinoth@psdigitise.com'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'Info@vysyamala.com'
EMAIL_HOST_PASSWORD = 'aussiopmcajislbs'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10  # Adjust based on needs
# }
