# Generated by Django 5.0.6 on 2024-06-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_religion_caste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caste',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='is_active',
        ),
    ]
