# Generated by Django 5.0.6 on 2024-06-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_familystatus_familytype_familyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caste',
            name='religion',
        ),
    ]
