# Generated by Django 5.0.6 on 2024-06-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_caste_religion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualincome',
            old_name='income',
            new_name='value',
        ),
    ]
