# Generated by Django 5.0.6 on 2024-06-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_income_annualincome_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualincome',
            old_name='value',
            new_name='income',
        ),
    ]
