# Generated by Django 5.0.6 on 2024-06-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_logindetailstemp'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='logindetailstemp',
        #     name='email',
        # ),
        migrations.RemoveField(
            model_name='logindetailstemp',
            name='id',
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='admin_permission',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='content_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='email_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='login_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='password',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='payment',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='payment_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='profile_complexion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='profile_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='profile_for',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='profile_height',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='profile_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp', 
            name='profile_marital_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='profile_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='stage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='logindetailstemp',
            table=None,
        ),
    ]
