# Generated by Django 5.0.6 on 2024-06-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_logindetailstemp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetailstemp',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='login_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='payment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='profile_complexion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='profile_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='profile_height',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='profile_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='profile_marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='profile_name',
            field=models.CharField(max_length=250),
        ),
    ]
