# Generated by Django 5.0.6 on 2024-06-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_logindetailstemp_email_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindetailstemp',
            table='LoginDetails_Temp',
        ),
    ]
