# Generated by Django 5.0.6 on 2024-06-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_logindetailstemp_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindetailstemp',
            table='masterloginvalue',
        ),
    ]
