# Generated by Django 5.0.6 on 2024-06-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_logindetailstemp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindetailstemp',
            table='logindetails_temp',
        ),
    ]
