# Generated by Django 5.0.6 on 2024-06-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_logindetailstemp_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindetailstemp',
            table=None,
        ),
    ]
