# Generated by Django 5.0.6 on 2024-06-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_logindetailstemp_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetailstemp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='logindetailstemp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='logindetailstemp',
            name='password',
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='AdminPermission',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='ContentId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='EmailId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='LoginId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Mobile_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='PaymentExpire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='PaymentType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='ProfileId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Profile_complexion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Profile_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Profile_for',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Profile_height',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Profile_marital_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Profile_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Stage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterModelTable(
            name='logindetailstemp',
            table='logindetails_temp',
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
