# Generated by Django 5.0.6 on 2024-06-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_logindetailstemp_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDetailsTemp',
        ),
    ]
