# Generated by Django 5.0.6 on 2024-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_delete_logindetailstemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetailsTemp',
            fields=[
                ('ContentId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProfileId', models.CharField(max_length=50, null=True)),
                ('LoginId', models.CharField(max_length=50, null=True)),
                ('Profile_for', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('Mobile_no', models.CharField(max_length=50, null=True)),
                ('EmailId', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Profile_name', models.CharField(max_length=250)),
                ('Profile_marital_status', models.CharField(max_length=100, null=True)),
                ('Profile_dob', models.DateField(null=True)),
                ('Profile_height', models.CharField(max_length=250)),
                ('Profile_complexion', models.CharField(max_length=100, null=True)),
                ('Otp', models.IntegerField(null=True)),
                ('Stage', models.PositiveSmallIntegerField(null=True)),
                ('AdminPermission', models.PositiveSmallIntegerField(null=True)),
                ('Payment', models.CharField(max_length=10, null=True)),
                ('PaymentExpire', models.DateTimeField(null=True)),
                ('PaymentType', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'logindetails_temp',
            },
        ),
    ]
