# Generated by Django 5.0.6 on 2024-06-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_logindetailstemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='AdminPermission',
            new_name='admin_permission',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='ContentId',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='EmailId',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='LoginId',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Mobile_no',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Otp',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='PaymentExpire',
            new_name='payment_expire',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='PaymentType',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Profile_complexion',
            new_name='profile_complexion',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Profile_dob',
            new_name='profile_dob',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Profile_height',
            new_name='profile_height',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='ProfileId',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Profile_marital_status',
            new_name='profile_marital_status',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Profile_name',
            new_name='profile_name',
        ),
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Stage',
            new_name='stage',
        ),
    ]
