# Generated by Django 5.0.6 on 2024-06-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_adminpermission_logindetailstemp_admin_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetailstemp',
            old_name='Profile_for',
            new_name='profile_for',
        ),
        migrations.RemoveField(
            model_name='logindetailstemp',
            name='content_id',
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
