# Generated by Django 5.0.6 on 2024-06-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_admin_permission_logindetailstemp_adminpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetailstemp',
            name='ContentId',
        ),
        migrations.AddField(
            model_name='logindetailstemp',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='AdminPermission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='EmailId',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='LoginId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='PaymentExpire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='PaymentType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='ProfileId',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Profile_complexion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Profile_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Profile_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Profile_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Profile_marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Profile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='Stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logindetailstemp',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='logindetailstemp',
            table=None,
        ),
    ]
