# Generated by Django 3.2.25 on 2024-06-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image_Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentoccupation',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('occupation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'masterparentsoccupation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilecity',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state_id', models.SmallIntegerField(max_length=20)),
                ('is_active', models.SmallIntegerField(max_length=1)),
            ],
            options={
                'db_table': 'masterdistrict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilecomplexion',
            fields=[
                ('complexion_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('complexion_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'complexionmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilecountry',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.SmallIntegerField(max_length=1)),
            ],
            options={
                'db_table': 'mastercountry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profileheights',
            fields=[
                ('height_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('height_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heightmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profileholder',
            fields=[
                ('Mode', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ModeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mastermode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileMaritalstatus',
            fields=[
                ('StatusId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('MaritalStatus', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maritalstatusmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilestate',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.SmallIntegerField(max_length=20)),
                ('is_active', models.SmallIntegerField(max_length=1)),
            ],
            options={
                'db_table': 'masterstate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration1',
            fields=[
                ('ContentId', models.AutoField(primary_key=True, serialize=False)),
                ('ProfileId', models.CharField(max_length=50)),
                ('LoginId', models.CharField(max_length=50)),
                ('Profile_for', models.CharField(max_length=50)),
                ('Gender', models.TextField(max_length=100)),
                ('Mobile_no', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('Otp', models.CharField(max_length=10)),
                ('Stage', models.SmallIntegerField(max_length=3)),
                ('AdminPermission', models.SmallIntegerField(max_length=3)),
                ('Payment', models.CharField(max_length=10)),
                ('PaymentExpire', models.DateTimeField(max_length=15)),
                ('PaymentType', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logindetails_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration2',
            fields=[
                ('ContentId', models.AutoField(primary_key=True, serialize=False)),
                ('ProfileId', models.CharField(max_length=50)),
                ('LoginId', models.CharField(max_length=50)),
                ('Profile_for', models.CharField(max_length=50)),
                ('Gender', models.TextField(max_length=100)),
                ('Mobile_no', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('Otp', models.CharField(max_length=10)),
                ('Stage', models.SmallIntegerField(max_length=3)),
                ('AdminPermission', models.SmallIntegerField(max_length=3)),
                ('Payment', models.CharField(max_length=10)),
                ('PaymentExpire', models.DateTimeField(max_length=15)),
                ('PaymentType', models.CharField(max_length=255)),
                ('Profile_name', models.CharField(max_length=250)),
                ('Profile_marital_status', models.CharField(max_length=250)),
                ('Profile_Dob', models.CharField(max_length=250)),
                ('Profile_height', models.CharField(max_length=250)),
                ('Profile_complexion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'logindetails_temp',
                'managed': False,
            },
        ),
    ]
